const fs = require('fs');
const path = require('path');

// 59 Duplicate Branch IDs to remove
const duplicateBranchIds = new Set([
  // Dhaka (8)
  'branch_5',   // Ati <=> আটি (1312)
  'branch_24',  // Khalpar <=> খালপাড় (1324)
  'branch_25',  // Agla <=> আগলা (1323)
  'branch_52',  // Narisha <=> নারিশা (1332)
  'branch_60',  // Amin Bazar <=> আমিন বাজার (1348)
  'branch_61',  // Rajfulbariya <=> রাজফুলবাড়ীয়া (1347)
  'branch_81',  // Kalampur <=> কমলপুর (1351)
  'branch_107', // Matuail SO <=> মাতুয়াইল (1362)

  // Narayanganj (5)
  'branch_119', // Nabiganj <=> নবীগঞ্জ (1412)
  'branch_131', // Baronagar <=> বারো নগর (1441)
  'branch_132', // Bardi <=> বারোদি (1442)
  'branch_148', // Dhuptara <=> দুপ্তারা (1460)
  'branch_156', // Vulta <=> ভুলতা (1462)

  // Munshiganj (16)
  'branch_165', // Katakhali <=> কাঠাখালি (1503)
  'branch_185', // Rasulpur <=> রসুলপুর (1512)
  'branch_186', // Hosendi <=> হোসেন্দি (1511)
  'branch_198', // Baligaon <=> বালিগাও (1522)
  'branch_199', // Hasail <=> হাসাইল (1524)
  'branch_200', // Pura <=> পুরা (1527)
  'branch_221', // Gawraganj <=> গৌড়গঞ্জ (1534)
  'branch_222', // Haridia <=> হারিদিয়া (1333 / 1533)
  'branch_223', // Korhati <=> করহাতি (1531)
  'branch_224', // Medinimondol <=> মেদিনী মণ্ডল (1335 / 1535)
  'branch_235', // Komarvogh <=> কুমারভগ (1555)
  'branch_267', // Kolapara <=> কলাপাড়া (1554)
  'branch_268', // Baghra <=> বাঘড়া (1557)
  'branch_269', // Maijpara <=> মাজপাড়া (1552)
  'branch_270', // Rarikhal <=> বারিখাল (1551)
  'branch_283', // Baroikhali <=> বারিখাল (1551)

  // Narsingdi (5)
  'branch_287', // Karimpur <=> করিমপুর (1605)
  'branch_308', // Charsindhur <=> চরসিন্ধুর (1612)
  'branch_333', // Bailab <=> বেলাব (1640)
  'branch_350', // Radhaganj <=> রাধাগঞ্জ বাজার (1632)
  'branch_351', // Bazar Hasnabad <=> বাজার হাসনাবাদ (1631)

  // Gazipur (5)
  'branch_434', // Pubail <=> পুবাইল (1721)
  'branch_435', // Chandona <=> চান্দনা (1702)
  'branch_521', // Rajendropur Bazar <=> রাজেন্দ্রপুর (1741)
  'branch_522', // Satkhamair <=> সাতখামার (1744)
  'branch_561', // Safipur Bazar <=> সফিপুর (1751)

  // Manikganj (7)
  'branch_565', // Gorpara <=> গড়পাড়া (1802)
  'branch_566', // Borong Gail <=> বরংগাইল (1804)
  'branch_567', // Mohadebpur <=> মহাদেবপুর (1803)
  'branch_568', // Manikgonj Bazar <=> মানিকগঞ্জ বাজার (1801)
  'branch_569', // Teota <=> তেওতা (1852)
  'branch_570', // Uthuli <=> উঠলি (1853)
  'branch_610', // Bayra <=> বায়রা (1821)

  // Tangail (9)
  'branch_638', // Hinganagar <=> হিংগা নগর (1914)
  'branch_639', // Pathrail <=> পাঠারাইল (1912)
  'branch_641', // Lauhati <=> লউহাটি (1915)
  'branch_649', // Mirzapur Cadet College <=> এম.সি. কলেজ (1942)
  'branch_650', // Kochua <=> কচুয়া (1951)
  'branch_659', // Nagbari <=> নাগবাড়ি (1972)
  'branch_666', // Jahidganj <=> জাহিদগঞ্জ (1981)
  'branch_667', // D Pakutiya <=> ডি পাকুটিয়া (1982)
  'branch_670', // Rajafoir <=> রাজাফাইর (1971)

  // Kishoreganj (3)
  'branch_680', // Nilganj <=> নীলগঞ্জ (2303)
  'branch_730', // Maijhati EDSO <=> মাইজহাটি (2302)
  'branch_744', // Gachhi Hata SO <=> গচিহাটা (2331)

  // Netrokona (1)
  'branch_784'  // Shaldigha <=> শালদিঘা (2462)
]);

// Place name dictionary for authentic Bangladeshi Bengali transliteration
const dictionary = {
  // Common prefixes & modifiers
  'uttar': 'উত্তর', 'uttor': 'উত্তর', 'dokkhin': 'দক্ষিণ', 'dakkhin': 'দক্ষিণ', 'south': 'দক্ষিণ', 'north': 'উত্তর',
  'purba': 'পূর্ব', 'purbo': 'পূর্ব', 'paschim': 'পশ্চিম', 'moddho': 'মধ্য', 'modda': 'মধ্য', 'choto': 'ছোট', 'boro': 'বড়',
  'notun': 'নতুন', 'puran': 'পুরান', 'bazar': 'বাজার', 'hat': 'হাট', 'char': 'চর', 'nagar': 'নগর', 'pur': 'পুর',
  'para': 'পাড়া', 'gaon': 'গাঁও', 'gram': 'গ্রাম', 'kandi': 'কান্দি', 'tola': 'তোলা', 'toli': 'তলী', 'bari': 'বাড়ী',
  'bariya': 'বাড়িয়া', 'baria': 'বাড়িয়া', 'diya': 'দিয়া', 'dia': 'দিয়া', 'dighi': 'দিঘী', 'pukur': 'পুকুর',
  'chala': 'চালা', 'khola': 'খোলা', 'bagh': 'বাগ', 'bag': 'বাগ', 'ganj': 'গঞ্জ', 'gonj': 'গঞ্জ',
  'sadar': 'সদর', 'college': 'কলেজ', 'madrasa': 'মাদ্রাসা', 'mills': 'মিলস', 'mill': 'মিল',
  'chawk': 'চক', 'chowk': 'চক', 'bondo': 'বন্দ', 'khal': 'খাল', 'par': 'পাড়', 'ghat': 'ঘাট',
  'tek': 'টেক', 'mor': 'মোড়', 'mora': 'মোড়া', 'konda': 'কোন্ডা', 'somiti': 'সমিতি', 'somiti hat': 'সমিতি হাট',

  // Dhaka
  'ashrafabad': 'আশরাফাবাদ',
  'uttar pangaon': 'উত্তর পানগাঁও',
  'konda': 'কোন্ডা',
  'baktarchar': 'বক্তারচর',
  'talepur': 'তালেপুর',
  'beuta': 'বেউতা',
  'baghoir': 'বাঘৈর',
  'paschimdi': 'পশ্চিমদী',
  'rahitpur': 'রোহিতপুর',
  'brahammankirti': 'ব্রাহ্মণকীর্তি',
  'rajabari': 'রাজাবাড়ী',
  'shakta': 'শাক্তা',
  'shyamlapur': 'শ্যামলাপুর',
  'shuvadda': 'শুভাঢ্যা',
  'sonakanda': 'সোনাকান্দা',
  'doleshor': 'দলেশ্বর',
  'teghoria': 'তেঘরিয়া',
  'par gandaria': 'পার গেন্ডারিয়া',
  'abdullapur': 'আব্দুল্লাহপুর',
  'itavara': 'ইটাভাড়া',
  'taranagar': 'তারানগর',
  'kharakandi': 'খাড়াকান্দি',
  'kolakopa': 'কলাকোপা',
  'gobindopur': 'গোবিন্দপুর',
  'galimpur': 'গালিমপুর',
  'choto box nagar': 'ছোট বক্সনগর',
  'jalalchar': 'জালালচর',
  'paragram': 'পারাগ্রাম',
  'braha': 'ব্রাহা',
  'bardhanpara': 'বর্ধনপাড়া',
  'mohabbatpur': 'মহব্বতপুর',
  'mashail': 'মাশাইল',
  'sholla': 'শোল্লা',
  'kailail': 'কৈলাইল',
  'aona': 'আওনা',
  'patiljhap': 'পাতিলঝাপ',
  'meleng': 'মেলেন',
  'dakkhin balukhondo': 'দক্ষিণ বালুখণ্ড',
  'khanepur': 'খানেপুর',
  'dewtola': 'দেওতোলা',
  'kuthuri': 'কুঠুরি',
  'joykrishnapur': 'জয়কৃষ্ণপুর',
  'karpara': 'করপাড়া',
  'shikaripara': 'শিকারীপূরা',
  'hat baruakhali': 'হাট বারুয়াখালী',
  'tasulla banglabazar': 'তাসুল্লা বাংলাবাজার',
  'al-amin bazar': 'আল-আমিন বাজার',
  'harichandi': 'হরিচণ্ডী',
  'dohar': 'দোহার',
  'meghula': 'মেঘুলা',
  'aorangabad': 'আওরঙ্গবাদ',
  'kusumhati': 'কুসুমহাটি',
  'dokkhin braha': 'দক্ষিণ ব্রাহা',
  'jamalchar': 'জামালচর',
  'vakurta': 'ভাকুর্তা',
  'rajashon': 'রাজাশন',
  'hemayetpur': 'হেমায়েতপুর',
  'moshurikhola': 'মসুরীখোলা',
  'shobahanbagh': 'সোবহানবাগ',
  'nayarhat': 'নয়ারহাট',
  'biruliya': 'বিরুলিয়া',
  'nagarkonda': 'নগরকোন্ডা',
  'ashuliya': 'আশুলিয়া',
  'zirabo': 'জিরাবো',
  'barabo': 'বরাবো',
  'perabo': 'প্যারাবো',
  'gobindapur': 'গোবিন্দপুর',
  'amlabo': 'আমলাবো',
  'birabo': 'বিরাবো',
  'crp chapain': 'সিআরপি চাপাইন',
  'mirzanagar': 'মির্জানগর',
  'senwaliya': 'সেনওয়ালিয়া',
  'noihati bazar': 'নৈহাটি বাজার',
  'karimpur': 'করিমপুর',
  'uttor gazirchat': 'উত্তর গাজীচট',
  'dhamsona': 'ধামসোনা',
  'balia': 'বালিয়া',
  'amta': 'আমতা',
  'dimukha': 'দিমুখা',
  'barigaon': 'বাড়ীগাঁও',
  'toperbari': 'টোপেরবাড়ী',
  'suapur': 'সুয়াপুর',
  'deldha': 'দেলধা',
  'shoilain': 'শৈলান',
  'jadabpur': 'যাদবপুর',
  'berosh': 'বেরোশ',
  'bannal': 'বান্নাল',
  'mangalbari': 'মঙ্গলবাড়ী',
  'nannar': 'নান্নার',
  'jalsin': 'জালসিন',
  'rowail': 'রোয়াইল',
  'kathaliya nabogram': 'কাঠালিয়া নবগ্রাম',
  'sanora': 'সানোড়া',
  'nowga bazar': 'নওগাঁ বাজার',
  'gangutiya': 'গাঙ্গুটিয়া',
  'jalsha': 'জালশা',
  'sahabelishwar': 'সাহাবেলীশ্বর',
  'chowhatto': 'চৌহাট',
  'rajapur': 'রাজাপুর',
  'purbagram': 'পূর্বগ্রাম',
  'tarab': 'তারাব',
  'jatramura': 'যাত্রামুড়া',
  'paradgair': 'প্যারাদগাইর',
  'sanarpar': 'সানারপাড়',
  'tushardhara': 'তুষারধারা',
  'merajnagar': 'মেরাজনগর',
  'habibnagar': 'হাবিবনগর',

  // Narayanganj
  'barabo': 'বরাবো',
  'madanpur': 'মদনপুর',
  'lakkhankhola': 'লক্ষণখোলা',
  'sabdibazar': 'সাবদী বাজার',
  'mogolergaon': 'মোগলেরগাঁও',
  'hosenpur': 'হোসেনপুর',
  'barpara': 'বারপাড়া',
  'monarbari': 'মোনারবাড়ী',
  'puran bandar': 'পুরান বন্দর',
  'jalkuri': 'জালকুড়ি',
  'vuighar': 'ভুঁইগড়',
  'dapa idrikpur': 'দাপা ইদ্রাকপুর',
  'kutubpur': 'কুতুবপুর',
  'anayetnagar': 'এনায়েতনগর',
  'char baktabali': 'চর বক্তাবলী',
  'alirtek': 'আলীরটেক',
  'kachpur': 'কাঁচপুর',
  'mizmizi': 'মিজমিজি',
  'siddirgonj bazar': 'সিদ্ধিরগঞ্জ বাজার',
  'highshadi': 'হাইশাদী',
  'lakshibardi': 'লক্ষ্মীবরদী',
  'dhandi bazar': 'ধান্দী বাজার',
  'saheb bazar': 'সাহেব বাজার',
  'bangla bazar': 'বাংলা বাজার',
  'ananda bazar': 'আনন্দ বাজার',
  'samomandi': 'সামোমন্দি',
  'aminpur': 'আমিনপুর',
  'new town': 'নিউ টাউন',
  'alipura': 'আলীপুরা',
  'nayanabad': 'নয়নাবাদ',
  'mohajampur': 'মহজমপুর',
  'kasem nagar': 'কাশেম নগর',
  'kala paharia': 'কালাপাহাড়িয়া',
  'hamshadi': 'হামশাদী',
  'pachrukhi': 'পাঁচরুখী',
  'sultansadi': 'সুলতানসাদী',
  'chaitonnokanda': 'চৈতন্যকান্দা',
  'sombupura': 'শম্ভুপুরা',
  'fausha': 'ফাউসা',
  'sreenibasdi': 'শ্রীনিবাসদী',
  'chardigaldi': 'চরদীঘলদী',
  'perabo': 'প্যারাবো',
  'baliapara': 'বালিয়াপাড়া',
  'nagarpara': 'নগরপাড়া',
  'parshinagar': 'পার্শীনগর',
  'masumabad': 'মাসুমাবাদ',
  'brahammonkhali': 'ব্রাহ্মণখালী',
  'rupshi': 'রূপসী',

  // Munshiganj
  'panchasar': 'পঞ্চসার',
  'ramjanbeg': 'রমজানবেগ',
  'tb hoghla': 'টিবি হোগলা',
  'jazira sayedpur': 'জাজিরা সৈয়দপুর',
  'vasanchar': 'ভাসানচর',
  'champatala': 'চম্পাতলা',
  'char dumoria': 'চর ডুমুরিয়া',
  'kewar': 'কেওয়ার',
  'gashi pukurpar': 'গাছী পুকুরপাড়',
  'makohati': 'মাকোহাটি',
  'char kishoreganj': 'চর কিশোরগঞ্জ',
  'coartgaon': 'কোর্টগাঁও',
  'moheshpur': 'মহেশপুর',
  'banial vokailash': 'বানিয়াল ভকৈলাশ',
  'char siloi': 'চর শিলই',
  'sokhabaspur': 'সোখাবাসপুর',
  'kalir atpara': 'কালীর আটপাড়া',
  'ramsing': 'রামসিং',
  'rampal': 'রামপাল',
  'voberchar': 'ভবেরচর',
  'bk raypura': 'বিকে রায়পুরা',
  'baosia': 'বাউশিয়া',
  'char bolaki': 'চর বলাকী',
  'goagasia': 'গুয়াগাছিয়া',
  'hoglakandi': 'হোগলাকান্দি',
  'ishmandirchar': 'ইশমন্দিরচর',
  'tengarchar': 'টেঙ্গারচর',
  'uttar shapur': 'উত্তর শাহপুর',
  'modda vaterchar': 'মধ্য ভাতেরচর',
  'puran baosia': 'পুরান বাউশিয়া',
  'ariol': 'আড়িয়াল',
  'outshahi': 'আউটশাহী',
  'dheepur': 'ধীপুর',
  'baloi': 'বালোই',
  'sonarong': 'সোনারং',
  'rawothvogh': 'রাউতভোগ',
  'jashlong': 'যশলং',
  'porapara': 'পোড়াপাড়া',
  'sornagram': 'স্বর্ণগ্রাম',
  'bagia': 'বাগিয়া',
  'molchar': 'মোলচর',
  'banari': 'বানারী',
  'nasongkar': 'নাসংকার',
  'pachgaon': 'পাঁচগাঁও',
  'b paikpara': 'বি পাইকপাড়া',
  'hatkan': 'হাটকান',
  'rahimganj': 'রহিমগঞ্জ',
  'aldi bazar': 'আলদী বাজার',
  'kaichail': 'কৈচাইল',
  'nagerhat': 'নাগেরহাট',
  'kalma': 'কলমা',
  'vorakor': 'ভড়কর',
  'jaotia': 'জাওতিয়া',
  'bejgaon': 'বেজগাঁও',
  'voghdia': 'ভোগদিয়া',
  'gaodia': 'গাওদিয়া',
  'konaksar': 'কনকসার',
  'kokotia': 'কোকটিয়া',
  'bahor': 'বহর',
  'beltoli': 'বেলতলী',
  'dokkhin charigaon': 'দক্ষিণ চারীগাঁও',
  'bibondi': 'বিবিন্দী',
  'bultoli': 'বুলতলী',
  'paschim nawpara': 'পশ্চিম নওপাড়া',
  'khidirpara': 'খিদিরপাড়া',
  'nawpara': 'নওপাড়া',
  'jasaldia': 'যশলদিয়া',
  'brojenhati': 'ব্রজেনহাটি',
  'kochiamora': 'কুচিয়ামোড়া',
  'latobdi': 'লতব্দী',
  'razdia': 'রাজদিয়া',
  'ramkrishnadi': 'রামকৃষ্ণদী',
  'rasunia': 'রশুনিয়া',
  'tolbasail': 'তৈলবাসাইল',
  'sikarpur nimtola': 'শিকারপুর নিমতলা',
  'chandandol': 'চন্দনধূল',
  'jainashar': 'জৈনসার',
  'kusumpur': 'কুসুমপুর',
  'shialdi': 'শিয়ালদী',
  'jazpur': 'জাজপুর',
  'b khilgaon': 'বি খিলগাঁও',
  'b moddhapara': 'বি মধ্যপাড়া',
  'khasmohal balurchar': 'খাসমহল বালুরচর',
  'malpadia': 'মালপদিয়া',
  'paoldia': 'পাওলদিয়া',
  'shimulia': 'শিমুলিয়া',
  'chitracoat': 'চিত্রকোট',
  'pawshar': 'পাউশার',
  'rajanagar': 'রাজনগর',
  'sayedpur': 'সৈয়দপুর',
  'solaghar': 'ষোলঘর',
  'purbo deovogh': 'পূর্ব দেওভোগ',
  'gadighat': 'গাদিঘাট',
  'koykirton': 'কয়কীর্তন',
  'damla': 'দামলা',
  'dokkhin paiksha': 'দক্ষিণ পাইকশা',
  'kazir pagla': 'কাজীর পাগলা',
  'dogachi': 'ডোগাছী',
  'atpara': 'আটপাড়া',
  'mojidpur': 'মজিদপুর',
  'rushdi': 'রুশদী',
  'tantar': 'তন্তুর',
  'katiapara': 'কাটিয়াপাড়া',
  'kamargaon': 'কামারগাঁও',
  'uttar raypura': 'উত্তর রায়পুরা',

  // Narsingdi
  'satgram': 'সাতগ্রাম',
  'collectorate bhabon': 'কালেক্টরেট ভবন',
  'amdiya': 'আমদিয়া',
  'balusair': 'বালুসাইর',
  'vatpara': 'ভাটপাড়া',
  'shekherchar': 'শেখেরচর',
  'shilmandi': 'শিলমান্দী',
  'baghhat': 'বাঘাহাট',
  'noyapara': 'নয়াপাড়া',
  'jameya e kashemiya': 'জামিয়া-ই-কাসেমিয়া',
  'panchoboti': 'পঞ্চবটী',
  'najorpur': 'নজরপুর',
  'meghna bazar': 'মেঘনা বাজার',
  'm pachgaon': 'এম পাঁচগাঁও',
  'rasulpur': 'রসুলপুর',
  'nuralapur': 'নুরালাপুর',
  'nowagaon': 'নওয়াগাঁও',
  'chinbalapur': 'চিনবালাপুর',
  'kathalia': 'কাঠালিয়া',
  'shantanpara': 'সান্তানপাড়া',
  'khas hawla': 'খাস হাওলা',
  'gayeshpur': 'গায়েশপুর',
  'noakanda bazar': 'নোয়াকান্দা বাজার',
  'sayederkhola': 'সৈয়দেরখোলা',
  'paruliya': 'পারুলিয়া',
  'dokkhin sadarchar': 'দক্ষিণ সর্দারচর',
  'jinadi': 'জিনারদী',
  'jasor bazar': 'যশোর বাজার',
  'nowkaghat': 'নৌকাঘাট',
  'kamrab': 'কামরাব',
  'chotobondo': 'ছোটবন্দ',
  'chaitonno': 'চৈতন্য',
  'joynagar': 'জয়নগর',
  'uttar agarpur': 'উত্তর আগরপুর',
  'kumartek': 'কুমারটেক',
  'putiyabari': 'পুটিয়াবাড়ী',
  'dakkhin agarpur': 'দক্ষিণ আগরপুর',
  'hossenpur': 'হোসেনপুর',
  'dottergaon': 'দত্তেরগাঁও',
  'dulalpur': 'দুলালপুর',
  'dhanua telikandi': 'ধানুয়া তেলিকান্দি',
  'nimgaon pulehat': 'নিমগাঁও পুলেহাট',
  'khariya': 'খারিয়া',
  'baghab': 'বাঘাব',
  'borokanda': 'বড়কান্দা',
  'uttor sadarchar': 'উত্তর সর্দারচর',
  'satpara': 'সাতপাড়া',
  'sunakura bazar': 'সুনাকুড়া বাজার',
  'mojlispur': 'মজলিশপুর',
  'ghorbari': 'ঘড়বাড়ী',
  'paratola': 'পাড়াতলা',
  'purandiya bazar': 'পুরানদিয়া বাজার',
  'kalinagar': 'কালীনগর',
  'lakhpur': 'লাখপুর',
  'kumardi': 'কুমারীদী',
  'kararchar': 'কারারচর',
  'kundarpara': 'কুন্দারপাড়া',
  'noadiya': 'নোয়াদীয়া',
  'shashpur': 'শাশপুর',
  'sayednagar': 'সৈয়দনগর',
  'moddho nagar': 'মধ্যনগর',
  'ashramchar': 'আশ্রমচর',
  'borochar': 'বড়চর',
  'hashimpur': 'হাশিমপুর',
  'kohinur jute mills': 'কোহিনূর জুট মিলস',
  'kataghat': 'কাটাঘাট',
  'algi bazar': 'আলগী বাজার',
  'marjal': 'মরজাল',
  'bashgari': 'বাঁশগাড়ী',
  'ramnagar': 'রামনগর',
  'mirjarchar': 'মির্জারচর',
  'narayanpur': 'নারায়ণপুর',
  'paratoli': 'পাড়াতলী',
  'pirijkandi': 'পিরিজকান্দি',
  'pirpur': 'পীরপুর',
  'rajprasad': 'রাজপ্রাসাদ',
  'bakharnagar': 'বাখনগর',
  'saidabad': 'সৈয়দাবাদ',
  'sampara': 'সামপাড়া',
  'soudagorkandi': 'সওদাগরকান্দি',
  'sreenidhi': 'শ্রীনিধি',
  'mushapur pagla bazar': 'মুশাপুর পাগলা বাজার',
  'tulatoli': 'তুলাতলী',
  'sahebchar': 'সাহেবচর',
  'charmodhua': 'চরমধুয়া',
  'adiyabad': 'আদিয়াবাদ',
  'nilokkha': 'নিলক্ষ্যা',
  'alokbali': 'আলোকবালী',
  'rahimabad': 'রহিমাবাদ',
  'baghaikandi': 'বাঘাইকান্দি',
  'hairmara': 'হাইরমারা',
  'uttor mirzanagar': 'উত্তর মির্জানগর',
  'charsubuddhi': 'চরসুবুদ্ধি',
  'bot toli': 'বটতলী',
  'dowkarchar': 'দৌলতকান্দি চর',
  'hatubanga': 'হাতুভাঙ্গা',
  'lokkhipur': 'লক্ষ্মীপুর',
  'amlabo': 'আমলাবো',
  'dulalkandi': 'দুলালকান্দি',
  'hosennagar': 'হোসেননগর',
  'vaterchar': 'ভাতেরচর',
  'dewanerchar': 'দেওয়ানরচর',
  'boteswar': 'বটেশ্বর',
  'binnabaid': 'বিন্নাবাইদ',
  'dholipara': 'ধলীপাড়া',
  'vabla': 'ভাবলা',
  'char kashimnagar': 'চর কাশিমনগর',
  'poradia': 'পোড়াদিয়া',
  'dokkhin lakhpur': 'দক্ষিণ লাখপুর',
  'aouliakanda': 'আউলিয়া কান্দি',
  'ujilab': 'উজিলাব',
  'chandanpur': 'চন্দনপুর',
  'bir maijdiya': 'বীর মাইজদিয়া',
  'ekduriya': 'একদুয়ারিয়া',
  'khifirpur': 'খিদিবপুর',
  'charmandaliya': 'চরমন্দালিয়া',
  'chowrasta mowlovibazar': 'চৌরাস্তা মৌলভীবাজার',
  'chalakchar': 'চালাকচর',
  'tarakandi': 'তারাকান্দি',
  'norendropur': 'নরেন্দ্রপুর',
  'shekhergaon': 'শেখেরগাঁও',
  'sukundi': 'সুকুন্দী',
  'lebutola': 'লেবুতলা',
  'rampur': 'রামপুর',
  'gotashhiya': 'গোতাশিয়া',
  'alalpur': 'আলালপুর',
  'chula': 'চুলা',
  'uttor noadiya': 'উত্তর নোয়াদীয়া',
  'narandi': 'নরেন্দী',
  'doulotpur': 'দৌলতপুর',
  'savardiya': 'সাবারদিয়া',
  'baghadi chowrasta bazar': 'বাঘাদী চৌরাস্তা বাজার',
  'kahetergaon': 'কাহেতেরগাঁও',
  'boro mirzapur bazar': 'বড় মির্জাপুর বাজার',
  'borochapa': 'বড়চাপা',
  'krishnapur': 'কৃষ্ণপুর',
  'hafizpur': 'হাফিজপুর',

  // Gazipur
  'harbaid': 'হারবাইদ',
  'bogdadia': 'বগদাদীয়া',
  'mirashpara': 'মিরাসপাড়া',
  'tongi bazar': 'টঙ্গী বাজার',
  'kumun': 'কুমুন',
  'kalni': 'কালনী',
  'vawal bariya': 'ভাওয়াল বাড়িয়া',
  'kanaiya': 'কানাইয়া',
  'dhirashram': 'ধীরাশ্রম',
  'vabanipur': 'ভবানীপুর',
  'mirjapur': 'মির্জাপুর',
  'salna': 'সালনা',
  'kaultiya': 'কাউলতিয়া',
  'bitipara bazar': 'ভিটিপাড়া বাজার',
  'zirani bazar': 'জিরানী বাজার',
  'kodda bazar': 'কড্ডা বাজার',
  'nilnagar': 'নীলনগর',
  'kashimpur': 'কাশিমপুর',
  'sardagonj': 'সারদাগঞ্জ',
  'konabari': 'কোনাবাড়ী',
  'boro vabanipur': 'বড় ভবানীপুর',
  'kb bazar': 'কেবি বাজার',
  'gacha': 'গাছা',
  'ulukhola': 'উলুখোলা',
  'khasdaudpur': 'খাসদাউদপুর',
  'atlapur': 'আটলাপাড়া',
  'birabo': 'বিরাবো',
  'putinabazar': 'পুতিনাবাজার',
  'som notun bazar': 'সোম নতুন বাজার',
  'danga bazar': 'ডাঙ্গা বাজার',
  'nagori': 'নাগরী',
  'adijangalia': 'আদিজাঙ্গালিয়া',
  'boktarpur': 'বক্তারপুর',
  'fuldi': 'ফুলদী',
  'bhawal bhrahammangaon': 'ভাওয়াল ব্রাহ্মণগাঁও',
  'dubati madrasa': 'ডুবাটি মাদ্রাসা',
  'rangamatia': 'রাঙ্গামাটিয়া',
  'sauraid': 'সাওরাইদ',
  'kolapatua': 'কলাপাতুয়া',
  'deputipara': 'ডেপুটিপাড়া',
  'baghun': 'বাঘুন',
  'dokkhinbag': 'দক্ষিণবাগ',
  'vawal noapara': 'ভাওয়াল নোয়াপাড়া',
  'nurun bazar': 'নুরুন বাজার',
  'ajmatpur': 'আজমতপুর',
  'aral bazar': 'আড়াল বাজার',
  'khirati': 'খিরাতী',
  'gaghutiya': 'ঘাগুটিয়া',
  'singuya': 'সিংগুয়া',
  'pakiyab madrasa': 'পাকিয়াব মাদ্রাসা',
  'meruya madrasa': 'মেরুয়া মাদ্রাসা',
  'char nilokkhi': 'চর নিলক্ষী',
  'hasanpur': 'হাসানপুর',
  'sonmaniya': 'সনমানিয়া',
  'noruttampur': 'নরোত্তমপুর',
  'pachua hazir bazar': 'পাঁচুয়া হাজির বাজার',
  'tokenoyon bazar': 'টোকনয়ন বাজার',
  'verarchar': 'ভেরারচর',
  'barishab': 'বরিশাব',
  'birojali': 'বিরোজালী',
  'aralia bazar': 'আড়ালিয়া বাজার',
  'ikuriya': 'ইকুরিয়া',
  'khamer': 'খামের',
  'torgaon': 'তরগাঁও',
  'taragonj': 'তারাগঞ্জ',
  'pakbaghiya': 'পাকবাঘিয়া',
  'pabur': 'পাবুর',
  'vawal chandpur': 'ভাওয়াল চাঁদপুর',
  'raniganj bazar': 'রাণীগঞ্জ বাজার',
  'vawal narayanpur': 'ভাওয়াল নারায়ণগঞ্জ',
  'rawnait': 'রাওনাইট',
  'tilshuniya': 'তিলশুনিয়া',
  'fulbariya madrasa': 'ফুলবাড়ীয়া মাদ্রাসা',
  'pirojpur': 'পিরোজপুর',
  'charkhamer': 'চরখামের',
  'baghua': 'বাঘুয়া',
  'palashpur': 'পলাশপুর',
  'borunhat': 'বরুণহাট',
  'lohadi': 'লোহাদী',
  'amraid': 'আমরাইদ',
  'ulusara': 'উলুসারা',
  'kopaleshwar': 'কপালেশ্বর',
  'vuleshwar': 'ভুলেশ্বর',
  'rayed': 'রায়েদ',
  'singhoshree': 'সিংহশ্রী',
  'sohagpur': 'সোহাগপুর',
  'dumdiya': 'ডুমদিয়া',
  'basudebpur': 'বাসুদেবপুর',
  'marta': 'মার্তা',
  'gajipur bazar': 'গাজীপুর বাজার',
  'goshinga': 'গোসিঙ্গা',
  'gila beraid': 'গিলা বেরাইদ',
  'tengra': 'টেংরা',
  'doni borotopa': 'ধনী বরতোপা',
  'boiragir chala': 'বৈরাগীর চালা',
  'mawna': 'মাওনা',
  'telihati': 'তেলিহাটি',
  'nij mawna': 'নিজ মাওনা',
  'latifpur': 'লতিফপুর',
  'kewa bazar': 'কেওয়া বাজার',
  'vawal rajabari': 'ভাওয়াল রাজাবাড়ী',
  'nolgaon': 'নলগাঁও',
  'faogain': 'ফাওগাইন',
  'damdoma': 'দমদমা',
  'vitipara': 'ভিটিপাড়া',
  'baldighat': 'বালদিঘাট',
  'hoydebpur': 'হায়দেবপুর',
  'bapta': 'বাপতা',
  'cha-bagan': 'চা-বাগান',
  'pirojali': 'পিরোজালী',
  'fulbariya': 'ফুলবাড়ীয়া',
  'boali': 'বোয়ালী',
  'raghunathpur': 'রঘুনাথপুর',
  'sakeshwar': 'সাকেশ্বর',
  'bashtoli': 'বাঁশতলী',
  'shahbajpur': 'শাহবাজপুর',
  'boliyadi': 'বলিয়াদী',
  'boroipara': 'বড়ইপাড়া',
  'gosatra': 'গোসাত্রা',
  'haturiyachala': 'হাতুরিয়াচালা',
  'araigonj hatkhola': 'আড়াইগঞ্জ হাটখোলা',
  'goalbathan': 'গোয়ালবাথান',
  'boroibai': 'বড়ইবাই',
  'boro gobindopur': 'বড় গোবিন্দপুর',
  'dewar bazar': 'দেওয়ান বাজার',
  'ratanpur': 'রতনপুর',
  'chandura': 'চান্দুরা',
  'mowchak': 'মৌচাক',

  // Manikganj
  'boikanthapur': 'বৈকুণ্ঠপুর',
  'balirtek': 'বালিরটেক',
  'baniyajuri': 'বানিয়াজুরী',
  'bongkhuri': 'বংখুরী',
  'boraid': 'বরাইদ',
  'boro hatkora': 'বড় হাতকোড়া',
  'barundi': 'বারুন্দী',
  'betila': 'বেতিলা',
  'brikaliyakoir': 'বৃকালিয়াকৈর',
  'chartilli': 'চরটিল্লী',
  'baraivikra': 'বড়াইভিকরা',
  'charghosta': 'চরঘোস্তা',
  'dhankora': 'ধানকোড়া',
  'v-tarail': 'ভি-তাড়াইল',
  'helachiya': 'হেলাচিয়া',
  'intajganj': 'ইন্তাজগঞ্জ',
  'jagir': 'জাগীর',
  'zanna bazar': 'জান্না বাজার',
  'zarina college': 'জরিনা কলেজ',
  'koitra': 'কৈত্রা',
  'koliya bazar': 'কলিয়া বাজার',
  'kellai': 'কেল্লাই',
  'koitora': 'কৈতরা',
  'khabaspur': 'খাবাসপুর',
  'lemubari': 'লেমুবাড়ী',
  'motto': 'মত্ত',
  'mitara': 'মিতরা',
  'muljan': 'মূলজান',
  'nabogram': 'নবগ্রাম',
  'pecharkanda': 'পেঁচারকান্দা',
  'pukhuriya': 'পুকুরিয়া',
  'ramdiyanali': 'রামদিয়ানালী',
  'sakrail': 'সাকরাইল',
  'chanka': 'চানকা',
  'tora': 'তরা',
  'shushunda': 'শুষুন্দা',
  'tilli': 'তিলী',
  'butuni': 'বুতনী',
  'atigram': 'আটিগ্রাম',
  'katigram': 'কাটিগ্রাম',
  'barahirchar': 'বারাহীরচর',
  'agsavar': 'আকসাভার',
  'dargram': 'দরগ্রাম',
  'gopalpur': 'গোপালপুর',
  'hargoj': 'হারগজ',
  'dighuliya': 'দিঘুলিয়া',
  'dholla bazar': 'ধল্লা বাজার',
  'charigram': 'চারিগ্রাম',
  'golardanga': 'গোলাড়ডাঙ্গা',
  'dokkhin jamsha': 'দক্ষিণ জামশা',
  'paril nowarda': 'পড়িল নওয়র্দা',
  'choto kaliakair': 'ছোট কালিয়াকৈর',
  'boldhara': 'বলধারা',
  'irta': 'ইরতা',
  'jamirta': 'জামির্তা',
  'chandahar': 'চান্দাহার',
  'sirajpur': 'সিরাজপুর',
  'sahrail': 'সাহরাইল',
  'chowdhury bowali': 'চৌধুরী বোয়ালী',
  'ibrahimpur': 'ইব্রাহিমপুর',
  'harukandi': 'হারুকান্দি',
  'jatrapur': 'যাত্রাপুর',

  // Tangail
  'mogra': 'মগড়া',
  'makorkol': 'মকরকোল',
  'atiya darga': 'আতিয়া দরগাহ',
  'koijuri': 'কৈজুরী',
  'aisora': 'আইসরা',
  'fulki jhanjhaniya': 'ফুলকী ঝাঝানিয়া',
  'tenguriyapara': 'তেঙ্গুরিয়াপাড়া',
  'konra': 'কন্দ্রা',
  'khash shahjani': 'খাস শাহজানী',
  'kuripara': 'কুড়িপাড়া',
  'indarjani': 'ইন্দারজানী',
  'nikrail': 'নিকরাইল',
  'palisha matikata': 'পালিশা মাটিকাটা',
  'charoshshua': 'চরঅশুয়া',
  'dhubliya': 'ধুবলিয়া',
  'nalin bazar': 'নলীন বাজার',
  'arjuna': 'অর্জুনা',
  'chati hati': 'ছাতিহাটী',
  'kadomtoli': 'কদমতলী',
  'kaliyagram': 'কালিয়াগ্রাম',
  'dewpara': 'দেওপাড়া',
  'bagundali': 'বাগুনডালী',
  'vabondotto': 'ভবনদত্ত',
  'shahi anuhola': 'শাহী আনুহোলা',
  'hadira bazar': 'হাদিরা বাজার',
  'vengua': 'ভেঙ্গুলা',
  'sholakura': 'শোলাকুড়া',

  // Kishoreganj
  'amirganj': 'আমিরগঞ্জ',
  'uradighi madrasa': 'উড়াদিঘী মাদ্রাসা',
  'kariyail': 'কড়িয়াইল',
  'bawlai': 'বৌলাই',
  'brahamankachori': 'ব্রাহ্মণকাচরী',
  'mathiya': 'মাঠিয়া',
  'jasodal': 'যশোদল',
  'kodaliya': 'কোদালিয়া',
  'chauddasata': 'চৌদ্দশত',
  'joybangla': 'জয়বাংলা',
  'binnati': 'বিন্নাটী',
  'salpamariya': 'শালমারা',
  'kodalatiya': 'কোদালিয়াটিয়া',
  'gujadia': 'গুজাদিয়া',
  'jangalbari': 'জঙ্গলবাড়ী',
  'joyka': 'জয়কা',
  'nansri': 'নানশ্রী',
  'parabaliya': 'পড়াবালিয়া',
  'niyamatpur': 'নিয়ামতপুর',
  'namapara': 'নামাপাড়া',
  'dehunada bazar': 'দেহুন্দা বাজার',
  'taljanga': 'তালজাঙ্গা',
  'damiha': 'দামিহা',
  'akubpur': 'আকুবপুর',
  'banail': 'বানাইল',
  'purba darijahangipur': 'পূর্ব দড়িজাহাঙ্গীরপুর',
  'purura': 'পুরুড়া',
  'jaoyar': 'জাওয়ার',
  'sekandor nagar': 'সেকান্দর নগর',
  'kajla bazar': 'কাজলা বাজার',
  'gangatiya': 'গাংগাটিয়া',
  'charpomdi': 'চরপমদী',
  'pumdi': 'পমদী',
  'surati': 'সুরতী',
  'ashutiya': 'আশুটিয়া',
  'kurimara': 'কুড়িমারা',
  'jamail': 'জামাইল',
  'shiplakandi': 'শিমুলকান্দি',
  'mechera': 'মেছেরা',
  'sahedal': 'সাহেদাল',
  'harenja': 'হারেনজা',
  'sukhia': 'সুখিয়া',
  'angiyadi': 'আংগিয়াদী',
  'charforadi': 'চরফরাদী',
  'taltala': 'তালতলা',
  'purba narandi': 'পূর্ব নরেন্দী',
  'pankchir': 'পাকচির',
  'bhadiya': 'ভাদিয়া',
  'mathkhola': 'মঠখোলা',
  'lakshia': 'লক্ষীয়া',
  'hosendi': 'হোসেন্দী',
  'patuabhanga': 'পটুয়াভাঙ্গা',
  'charkaona': 'চরকাওনা',
  'jangaliya': 'জাঙ্গালিয়া',
  'burudia': 'বুরুদিয়া',
  'kaladiya': 'কালাদিয়া',
  'bethair': 'বেথাইর',
  'acmita': 'আচমিতা',
  'moddhopara': 'মধ্যপাড়া',
  'union jalalpur': 'ইউনিয়ন জালালপুর',
  'boyalia': 'বোয়ালিয়া',
  'betal': 'বেতাল',
  'masuya': 'মসূয়া',
  'bairagirchar': 'বৈরাগীরচর',
  'mumurdia': 'মুমুরদিয়া',
  'jambait': 'জামবাইট',
  'charpukiya': 'চরপুকুরিয়া',
  'pardiyakul': 'পাড়দিয়াকুল',
  'manikkhali': 'মানিকখালী',
  'dhankipara': 'ধানকীগ্রাম',
  'catal': 'চাতল',

  // Netrokona
  'raydomrouha': 'রায়দমড়ৌহা',
  'bilkaushi': 'বিলকাউশী',
  'hironpur': 'হিরণপুর',
  'munshirhat': 'মুন্সীরহাট',
  'goatola': 'গোয়াতলা',
  'ketta': 'কেত্তা',
  'atithpur': 'অতিথপুর',
  'thakurkona': 'ঠাকুরকোনা',
  'rupganj': 'রূপগঞ্জ',
  'dashdhar': 'দশধার',
  'shunoy': 'শুনই',
  'fakirer bazar': 'ফকিরের বাজার',
  'raypur': 'রায়পুর',
  'sahta': 'সাহতা',
  'uttorbir': 'উত্তরবীর',
  'deola': 'দেওলা',
  'badshgonj': 'বাদশাগঞ্জ',
  'joysree': 'জয়শ্রী',
  'paikurati': 'পাইকুরাটি',
  'golokpur': 'গোলকপুর',
  'sukhair': 'সুখাইড়',
  'selimgonj': 'সেলিমগঞ্জ',
  'kolunka': 'কলুঙ্কা',
  'southpara': 'দক্ষিণপাড়া',
  'chamardani': 'চামারদানী',
  'bongshikunda': 'বংশীকুন্ডা',
  'farokh nagar': 'ফারুক নগর',
  'abid nagar': 'আবিদ নগর',
  'kartikpur': 'কার্তিকপুর',
  'pach hat': 'পাঁচ হাট',
  'bolli': 'বল্লী',
  'trimohoni': 'ত্রিমোহনী',
  'nurpur boali': 'নূরপুর বোয়ালী',
  'mukimpur': 'মুকিমপুর',
  'khila': 'খিলা',
  'modhuakhali': 'মধুয়াখালী',
  'luneshwar': 'লুনেশ্বর',
  'avoypasha': 'অভয়পাশা',
  'koilong': 'কৈলং',
  'chargatiya': 'চরগাতিয়া',
  'teligati': 'তেলিগাতী',
  'dijara': 'দিজারা',
  'mangolshiddi': 'মঙ্গলসিদ্ধি',
  'ramsiddo': 'রামসিদ্ধ',
  'sharomshiya': 'সারমসিয়া',
  'shukhari': 'সুখারী',
  'paikura': 'পাইকুড়া',
  'satashidigar': 'সাতাশীদিগর',
  'hararkandi': 'হাড়ারকান্দি',
  'sandikona': 'সান্ডিকোনা',
  'bhuiyar bazar': 'ভূঁইয়ার বাজার',
  'machiali': 'মাছিয়ালী',
  'bashati': 'বসতি',
  'durcapur': 'দুর্গাপুর',
  'bidyaballabha': 'বিদ্যাবল্লভ',
  'baghber': 'বাঘবেড়',
  'balijora': 'বালিজোড়া',
  'gonda': 'গন্ডা',
  'goradoba': 'গড়াদোবা',
  'kailati phatepur': 'কৈলাটি ফতেপুর',
  'kachimpur': 'কাচিমপুর',
  'kaliyan': 'কালিয়ান',

  // Chattogram
  'nnm madrasa': 'এনএনএম মাদ্রাসা',
  'jafar nagar': 'জাফর নগর',
  'muradpur': 'মুরাদপুর',
  'kamar ali': 'কামার আলী',
  'choto daroga hat': 'ছোট দারোগাহাট',
  'domkhali somiti hat': 'ডোমখালী সমিতি হাট',
  'boro daroga hat': 'বড় দারোগাহাট',
  'baliadi': 'বালিয়াদী',
  'mohanagar': 'মহানগর',
  'shekher hat': 'শেখের হাট',
  'shitolpur': 'শীতলপুর',
  'hafiz jute mills': 'হাফিজ জুট মিলস',
  'dakkhin shitolpur raja kashem': 'দক্ষিণ শীতলপুর রাজা কাশেম',
  'komoldoho': 'কমলদহ',
  'nijampur college': 'নিজামপুর কলেজ',
  'hadi fakirhat': 'হাদী ফকিরহাট',
  'haid kandi': 'হাইদ কান্দি',
  'mithanala': 'মিঠানালা',
  'bortakiya': 'বড়তাকিয়া',
  'moliaish': 'মলিয়াশ',
  'mithachara': 'মিঠাছড়া',
  'sufiya madrasa': 'সুফিয়া মাদ্রাসা',
  'bongnur': 'বঙ্গনূর',
  'eshak driver hat': 'ইসহাক ড্রাইভার হাট',
  'abur hat': 'আবুড় হাট',
  'choitonner hat': 'চৈতন্যের হাট',
  'temuhoni': 'তেমুহনী',
  'bishu mia hat': 'বিশু মিয়া হাট',
  'matbar hat': 'মাতব্বর হাট',
  'poragolpur': 'পরাগালপুর',
  'mobarok ghona': 'মোবারক ঘোনা',
  'shantir hat': 'শান্তির হাট',
  'hinguli': 'হিঙ্গুলী',

  // Kurigram
  'tapurchar': 'টাপুরচর',
  'naiyarhati': 'নায়ারহাটি',
  'jadurchar': 'যাদুরচর',
  'char shoulomari': 'চর শৌলমারী',
  'dadvanga': 'দাঁদভাঙ্গা',
  'baghurarchar': 'বাঘুরারচর',
  'shoulmari': 'শৌলমারী',
  'kodalkati': 'কোদালকাটি',

  // Sirajganj
  'kumariyabari': 'কুমারিয়া বাড়ী',
  'chargrish': 'চরগিরিশ',

  // Sunamganj & Habiganj
  'mahmudpur': 'মাহমুদপুর',
  'kumri durgapur': 'কুমড়ী দুর্গাপুর'
};

function getBengaliName(englishName) {
  if (!englishName) return '';
  // Clean prefixes/suffixes (only match uppercase tags with whitespace)
  let clean = englishName
    .replace(/\s+(EDBO|EDSO|TSO|SO|B\.?O\.?)\b/g, '')
    .trim();

  const lower = clean.toLowerCase();
  if (dictionary[lower]) {
    return dictionary[lower];
  }

  // Tokenize
  const parts = clean.split(/\s+/);
  const bnParts = parts.map(p => {
    const pLow = p.toLowerCase();
    if (dictionary[pLow]) return dictionary[pLow];
    return p;
  });

  return bnParts.join(' ');
}

// Build mapping for upazilas from English to Bengali
const upazilaBnMap = {
  'Kamrangirchar': 'কামরাঙ্গীরচর',
  'Keranigonj': 'কেরানীগঞ্জ',
  'Nawabgonj': 'নবাবগঞ্জ',
  'Joypara (Dohar)': 'দোহার',
  'Savar': 'সাভার',
  'Dhamrai': 'ধামরাই',
  'Demra': 'ডেমরা',
  'Kodomtoli': 'কদমতলী',
  'Sadar': 'সদর',
  'Bandar': 'বন্দর',
  'Fatulla': 'ফতুল্লা',
  'Siddirgonj': 'সিদ্ধিরগঞ্জ',
  'Sonargaon': 'সোনারগাঁও',
  'Arhaihazar': 'আড়াইহাজার',
  'Rupgonj': 'রূপগঞ্জ',
  'Gazaria': 'গজারিয়া',
  'Tongibari': 'টঙ্গীবাড়ী',
  'Louhajong': 'লৌহজং',
  'Serajdi Khan': 'সিরাজদিখান',
  'Sreenagar': 'শ্রীনগর',
  'Palash': 'পলাশ',
  'Shibpur': 'শিবপুর',
  'Raipura': 'রায়পুরা',
  'Belabo': 'বেলাবো',
  'Monohardi': 'মনোহরদী',
  'Narandi': 'নরসিংদী সদর',
  'Gazipur': 'গাজীপুর সদর',
  'Kaligonj': 'কালীগঞ্জ',
  'Kapasia': 'কাপাসিয়া',
  'Sreepur': 'শ্রীপুর',
  'kaliakair': 'কালিয়াকৈর',
  'Saturia': 'সাটুরিয়া',
  'Singair': 'সিংগাইর',
  'Lesragonj (Harirampur)': 'হরিরামপুর',
  'Deldoar': 'দেলদুয়ার',
  'Basail': 'বাসাইল',
  'Nagarpur': 'নাগরপুর',
  'Mirzapur': 'মির্জাপুর',
  'Shakhipur': 'সখিপুর',
  'Bhuapur': 'ভূঞাপুর',
  'Kalihati': 'কালিহাতী',
  'Ghatail': 'ঘাটাইল',
  'Gopalpur': 'গোপালপুর',
  'Madhupur': 'মধুপুর',
  'Nalitabari': 'নালিতাবাড়ী',
  'Karimgonj': 'করিমগঞ্জ',
  'Tarail': 'তাড়াইল',
  'Hussainpur': 'হোসেনপুর',
  'Pakundi': 'পাকুন্দিয়া',
  'Kathiadi': 'কটিয়াদী',
  'Purbadhala': 'পূর্বধলা',
  'Dhobaura': 'ধোবাউড়া',
  'Susang': 'দুর্গাপুর (সুসং)',
  'Barhatta': 'বারহাট্টা',
  'Dharampasa': 'ধর্মপাশা',
  'Madhya Nagar': 'মধ্যনগর',
  'Khaliajuri': 'খালিয়াজুরী',
  'Atpara': 'আটপাড়া',
  'Kendua': 'কেন্দুয়া',
  'Tahirpur': 'তাহিরপুর',
  'Baniachong': 'বানিয়াচং',
  'Sitakundu': 'সীতাকুণ্ড',
  'Mireshwarai': 'মীরসরাই',
  'Ulipur': 'উলিপুর',
  'Chilmari': 'চিলমারী',
  'Roumari': 'রৌমারী',
  'Rajibpur': 'চর রাজিবপুর',
  'Kazipur': 'কাজীপুর'
};

const districtStandardMap = {
  'ঢাকা': { bn: 'ঢাকা', en: 'Dhaka', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'নারায়নগঞ্জ': { bn: 'নারায়ণগঞ্জ', en: 'Narayanganj', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'মুন্সিগঞ্জ': { bn: 'মুন্সীগঞ্জ', en: 'Munshiganj', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'নরসিংদী': { bn: 'নরসিংদী', en: 'Narsingdi', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'গাজীপুর': { bn: 'গাজীপুর', en: 'Gazipur', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'মানিকগঞ্জ': { bn: 'মানিকগঞ্জ', en: 'Manikganj', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'টাঙ্গাইল': { bn: 'টাঙ্গাইল', en: 'Tangail', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'শেরপুর': { bn: 'শেরপুর', en: 'Sherpur', divBn: 'ময়মনসিংহ', divEn: 'Mymensingh' },
  'কিশোরগঞ্জ': { bn: 'কিশোরগঞ্জ', en: 'Kishoreganj', divBn: 'ঢাকা', divEn: 'Dhaka' },
  'নেত্রকোনা': { bn: 'নেত্রকোণা', en: 'Netrokona', divBn: 'ময়মনসিংহ', divEn: 'Mymensingh' },
  'সুনামগঞ্জ': { bn: 'সুনামগঞ্জ', en: 'Sunamganj', divBn: 'সিলেট', divEn: 'Sylhet' },
  'হবিগঞ্জ': { bn: 'হবিগঞ্জ', en: 'Habiganj', divBn: 'সিলেট', divEn: 'Sylhet' },
  'চট্টগ্রাম': { bn: 'চট্টগ্রাম', en: 'Chattogram', divBn: 'চট্টগ্রাম', divEn: 'Chattogram' },
  'কুড়িগ্রাম': { bn: 'কুড়িগ্রাম', en: 'Kurigram', divBn: 'রংপুর', divEn: 'Rangpur' },
  'সিরাজগঞ্জ': { bn: 'সিরাজগঞ্জ', en: 'Sirajganj', divBn: 'রাজশাহী', divEn: 'Rajshahi' }
};

// Load base 858 records from crawl
const pmg = JSON.parse(fs.readFileSync('.scripts-archive/bdpost_pmgkhulna_all.json', 'utf8'));
const noCodeRecords = pmg.records.filter(r => !r.postCodeEn);
console.log('Original total no-code records in PMG:', noCodeRecords.length);

// Filter out duplicates
const revisedBranches = [];
let origId = 1;
let newId = 1;

noCodeRecords.forEach(r => {
  const currentBranchId = `branch_${origId++}`;
  if (duplicateBranchIds.has(currentBranchId)) {
    return; // Skip duplicate
  }

  const distInfo = districtStandardMap[r.district] || {
    bn: r.district,
    en: r.district,
    divBn: 'অন্যান্য',
    divEn: 'Other'
  };

  const thanaBn = upazilaBnMap[r.upazila] || r.upazila;
  const officeEn = r.postOfficeEn.trim();
  const isEdbo = /edbo/i.test(officeEn);
  const cleanEn = officeEn.replace(/\s+(EDBO|EDSO|TSO|SO|B\.?O\.?)\b/g, '').replace(/\s*edbo\s*/gi, '').trim();
  const bnName = getBengaliName(officeEn);

  revisedBranches.push({
    id: `branch_${newId}`,
    numericId: newId++,
    isBranchOffice: true,
    officeType: isEdbo ? 'EDBO' : 'Branch Office',
    divisionEn: distInfo.divEn,
    divisionBn: distInfo.divBn,
    districtEn: distInfo.en,
    districtBn: distInfo.bn,
    thanaBn: thanaBn,
    thanaEn: r.upazila,
    postOfficeEn: cleanEn,
    postOfficeBn: bnName,
    postCodeEn: '',
    postCodeBn: 'প্রযোজ্য নয়',
    rawPostCode: '',
    sourceUrl: r.sourceUrl
  });
});

console.log('Revised branch offices count:', revisedBranches.length);
console.log('Duplicates removed:', noCodeRecords.length - revisedBranches.length);

// Re-group by district
const districtMap = {};
revisedBranches.forEach(b => {
  if (!districtMap[b.districtEn]) {
    districtMap[b.districtEn] = {
      districtBn: b.districtBn,
      districtEn: b.districtEn,
      divisionBn: b.divisionBn,
      divisionEn: b.divisionEn,
      branchOffices: []
    };
  }
  districtMap[b.districtEn].branchOffices.push(b);
});

const outputData = {
  metadata: {
    title: 'Bangladesh Post Office - Branch Offices without Separate Post Code',
    titleBn: 'বাংলাদেশ ডাক বিভাগ - পোস্ট কোড বিহীন শাখা ডাকঘর তালিকা (EDBO/শাখা অফিস)',
    description: 'Extra Departmental Branch Offices (EDBO) listed under various upazilas that do not have their own unique post code and use their parent office postal delivery code.',
    source: 'Bangladesh Post Office (বাংলাদেশ ডাক অধিদপ্তর - PMG Khulna Portal)',
    sourceUrl: 'https://pmgkhulna.bdpost.gov.bd/pages/static-pages/6922dc0b933eb65569e0e1e5',
    totalBranchOffices: revisedBranches.length,
    totalDistricts: Object.keys(districtMap).length,
    generatedAt: new Date().toISOString()
  },
  districts: Object.values(districtMap),
  branchOffices: revisedBranches
};

// Write JSON
const jsonPath = path.resolve('.scripts-archive/branch_offices_no_postcode.json');
fs.writeFileSync(jsonPath, JSON.stringify(outputData, null, 2), 'utf8');

// Write JS file
const jsPath = path.resolve('src/data/branch-offices-data.js');
const jsContent = `/* Auto-generated Bangladesh Post Office - Branch Offices without Post Code */\nwindow.BD_BRANCH_OFFICES_DATA = ${JSON.stringify(outputData)};\n`;
fs.writeFileSync(jsPath, jsContent, 'utf8');

console.log(`Saved revised branch data:`);
console.log(`- ${jsonPath}`);
console.log(`- ${jsPath}`);
